### ISSUE TITLE
FEATURE: Parcel model results depend strongly on dz

### ISSUE THREAD

**Issue by claresinger** [open-atmos/PySDM#765]
We changed the parcel settings to run in `dz` not `dt` (for ease when running with many different `w`). When we did this, we noticed unexpected behavior, where the result of the equilibrium supersaturation reached for the parcel **strongly** depends on the `dz` used even when it is very small (1 m) where we don't think the piecewise constant pressure approximation should lead to any errors.

Minimal example to produce bug on this branch: https://github.com/claresinger/PySDM-examples/tree/ss_eq_error

fig 2 from Lowe example with dz=0.1 m
![fig2ab_dz=0 1](https://user-images.githubusercontent.com/6875824/153897996-8748f605-c221-4555-8e6e-e5530b8da7be.png)
fig 2 from Lowe example with dz=1 m
![fig2ab_dz=1](https://user-images.githubusercontent.com/6875824/153898003-bdc8ba82-a9ba-4a1a-a94a-37deddf0751e.png)

**Comment by slayoo** [comment]
Thank you, Clare!

**Comment by claresinger** [comment]
Maybe this https://github.com/atmos-cloud-sim-uj/PySDM/issues/746 should be a priority to implement!

**Comment by claresinger** [comment]
[fig_2ab_dz1.pdf](https://github.com/open-atmos/PySDM/files/10771164/fig_2ab_dz1.pdf)
[fig_2ab_dz001.pdf](https://github.com/open-atmos/PySDM/files/10771165/fig_2ab_dz001.pdf)
Just confirming this issue still exists. Should we try implementing #746 to fix it?

**Comment by slayoo** [comment]
@abulenok's #868 fixes a number of issues with parcel thermodynamics, likely worth checking it out first

**Comment by claresinger** [comment]
Is #868 going to be merged in soon? If not, I can check the dz sensitivity on that branch later this week.

**Comment by claresinger** [comment]
@slayoo @abulenok What's the status with #868 and https://github.com/open-atmos/PySDM-examples/pull/164 ?

**Comment by slayoo** [comment]
@claresinger, we've been actually focusing on condensation in the last weeks what resulted in reporting a bug report to Numba yesterday (it is a SciPy/Numba incompatibility): https://github.com/numba/numba/issues/8931 This is the reason why we intermittently get CI failures in condensation, and likely also related with the issues of condensation/parcel examples using the BDF solver taking actually almost half of the CI time (much more than 1D or 2D cases!)

BTW, if you know of any other BDF Python package that we could use instead of SciPy, this could be great to introduce (however, the key constraint is to not introduce any cumbersome dependencies).

Concerning the adaptivity criteria, I'll try to have a look again on these PRs and prepare a TODO list which could help us estimate how much effort is needed to finally switch from `thd` to `RH` as the adaptivity control base.

Thanks

**Comment by slayoo** [comment]
@claresinger, let's reopen this one till we have this test case in place as a unit test
